### ISSUE TITLE
Fully specified path for linux/gtk dlls?

### ISSUE THREAD

**Issue by emarcotte** [Mono-Game/MonoGame.Dependencies#39]
I was reading http://community.monogame.net/t/some-issues-with-pipeline-tool-on-fedora/1798 and the related pull request #3426 trying to figure out how to get the Pipeline tool working on fedora... One difference for me is that I am not using the Xamarin repository for mono I'm using https://build.opensuse.org/project/show/home:tpokorra:mono, which seems to work fine for everything I've needed.

I'm not very familiar with the blah.dll.config files, but why do they have fully specified paths to the various .so files? I am unable to get the Pipeline.exe to start with them that way. As the commenter on the community site suggests, making them just target="blah.so" works.

I'm willing to submit a pull request to make them not fully specified, but I don't understand why they should or shouldn't be one way or the other yet...

Thanks!
Eugene

**Comment by KonajuGames** [comment]
Nothing should use fully qualified paths.  No two systems are the same, and everything can be different on different distros or even different users using the same distro.  By distro, I'm also referring to Windows and OS X.

**Comment by dellis1972** [comment]
Just so people know, the OS X paths in the .dll.config files are required. Mono only installs in /Library/Frameworks/Mono.framework 
afaik. So we are safe on Mac with the configs as they are.

**Comment by cra0zy** [comment]
@tomspilman This can be closed because of #42
