### ISSUE TITLE
Missing Third Party Dependency, NAudio.dll?

### ISSUE THREAD

**Issue by olilittle** [Mono-Game/MonoGame.Dependencies#45]
Hi

When trying to build the MonogameContentProcessors project, visual studio throws up an error 

The type or namespace name 'NAudio' could not be found (are you missing a using directive or an assembly reference?)

When checking the project reference, it refers to an address in the third party dependencies folder that doesn't seem to exist in the depo.

Have I missed an instruction somewhere? 

Thanks

**Comment by tomspilman** [comment]
If you are trying to work from a 3.2 release of MonoGame you can get the binary dependencies for that here:

  https://github.com/Mono-Game/MonoGame.Dependencies/releases/tag/v3.2

If you are working from the `develop` branch you need to use this revision:

 https://github.com/Mono-Game/MonoGame.Dependencies/tree/a3b075f8d5f76a74d51bec6fc6490d262c7f0ddd

 ... you can download a zip on that page.

**Comment by cra0zy** [comment]
this explains everything: http://teamcity.monogame.net/viewLog.html?tab=buildLog&buildTypeId=MonoGame_DevelopWin&buildId=5712&state=4126%2C4129%2C4130%2C4369#_state=4126,4129,4130,4369&focus=4369

**Comment by cra0zy** [comment]
Very short explanation: @olilittle is using the newest dependencies with the newest develop branch, instead of using the @ a3b075f snapshot. I think this can be closed.
